/*
 * This Java source file was generated by the Gradle 'init' task.
 */
package mr.jar;

import org.junit.jupiter.api.Test;
import static org.junit.jupiter.api.Assertions.*;

class LibrarianTest {
    @Test void testSomeLibraryMethod() {
        Library classUnderTest = new Library();
        assertTrue(!classUnderTest.someLibraryMethod(), "someLibraryMethod should return 'true'");
    }
}
